name: update wiki
run-name: ${{ github.actor }} is updating wiki 🚀
on: [push]
jobs:
  Update-Wiki:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: github-docs-to-wiki
        uses: cmbrose/github-docs-to-wiki@v0.20
        with:
          repository: OpenPecha/stt-documentation